//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// prd 28-09-2021
namespace SAPReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInformationBillsHeader", Namespace="http://schemas.datacontract.org/2004/07/AllservicesIntegrationJepco.Classes")]
    public partial class CustomerInformationBillsHeader : object
    {
        
        private string BillingFactorField;
        
        private string BusinessPartnarField;
        
        private string ContractAccountField;
        
        private string ContractNumberField;
        
        private string EquipmentNumberField;
        
        private string FactorField;
        
        private string FileNumberField;
        
        private string FirstNameField;
        
        private string FranchiseContractField;
        
        private string InstallationField;
        
        private string InsuranceBalanceField;
        
        private string InternalNumberField;
        
        private string LastMeterReadingDateField;
        
        private string LastMeterReadingDateSAPFormatField;
        
        private string LastNameField;
        
        private string LastNetMeteringMeterReadField;
        
        private string LastNormalMeterReadField;
        
        private string MeterDigitsField;
        
        private string MeterNumberField;
        
        private string NextMeterReadingDateField;
        
        private string NextMeterReadingDateSAPFormatField;
        
        private string NumberOfRegistersField;
        
        private string OfficeCodeField;
        
        private string OfficeDescriptionField;
        
        private string OflagEmpField;
        
        private string PortionField;
        
        private string PreLastMeterReadingDateField;
        
        private string PreLastMeterReadingDateSAPFormatField;
        
        private string PreNetMeteringMeterReadField;
        
        private string PreNormalMeterReadField;
        
        private string RateFactorGroupField;
        
        private string ReceivableAmountField;
        
        private string RecievableBalanceField;
        
        private string RegisterFactorField;
        
        private string SettelmentBalanceField;
        
        private string SubscriptionCodeField;
        
        private string SubscriptionDescriptionField;
        
        private string SubscriptionNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingFactor
        {
            get
            {
                return this.BillingFactorField;
            }
            set
            {
                this.BillingFactorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessPartnar
        {
            get
            {
                return this.BusinessPartnarField;
            }
            set
            {
                this.BusinessPartnarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractAccount
        {
            get
            {
                return this.ContractAccountField;
            }
            set
            {
                this.ContractAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractNumber
        {
            get
            {
                return this.ContractNumberField;
            }
            set
            {
                this.ContractNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipmentNumber
        {
            get
            {
                return this.EquipmentNumberField;
            }
            set
            {
                this.EquipmentNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Factor
        {
            get
            {
                return this.FactorField;
            }
            set
            {
                this.FactorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileNumber
        {
            get
            {
                return this.FileNumberField;
            }
            set
            {
                this.FileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FranchiseContract
        {
            get
            {
                return this.FranchiseContractField;
            }
            set
            {
                this.FranchiseContractField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Installation
        {
            get
            {
                return this.InstallationField;
            }
            set
            {
                this.InstallationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InsuranceBalance
        {
            get
            {
                return this.InsuranceBalanceField;
            }
            set
            {
                this.InsuranceBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalNumber
        {
            get
            {
                return this.InternalNumberField;
            }
            set
            {
                this.InternalNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastMeterReadingDate
        {
            get
            {
                return this.LastMeterReadingDateField;
            }
            set
            {
                this.LastMeterReadingDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastMeterReadingDateSAPFormat
        {
            get
            {
                return this.LastMeterReadingDateSAPFormatField;
            }
            set
            {
                this.LastMeterReadingDateSAPFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastNetMeteringMeterRead
        {
            get
            {
                return this.LastNetMeteringMeterReadField;
            }
            set
            {
                this.LastNetMeteringMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastNormalMeterRead
        {
            get
            {
                return this.LastNormalMeterReadField;
            }
            set
            {
                this.LastNormalMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterDigits
        {
            get
            {
                return this.MeterDigitsField;
            }
            set
            {
                this.MeterDigitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterNumber
        {
            get
            {
                return this.MeterNumberField;
            }
            set
            {
                this.MeterNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextMeterReadingDate
        {
            get
            {
                return this.NextMeterReadingDateField;
            }
            set
            {
                this.NextMeterReadingDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextMeterReadingDateSAPFormat
        {
            get
            {
                return this.NextMeterReadingDateSAPFormatField;
            }
            set
            {
                this.NextMeterReadingDateSAPFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumberOfRegisters
        {
            get
            {
                return this.NumberOfRegistersField;
            }
            set
            {
                this.NumberOfRegistersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeCode
        {
            get
            {
                return this.OfficeCodeField;
            }
            set
            {
                this.OfficeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfficeDescription
        {
            get
            {
                return this.OfficeDescriptionField;
            }
            set
            {
                this.OfficeDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OflagEmp
        {
            get
            {
                return this.OflagEmpField;
            }
            set
            {
                this.OflagEmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Portion
        {
            get
            {
                return this.PortionField;
            }
            set
            {
                this.PortionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreLastMeterReadingDate
        {
            get
            {
                return this.PreLastMeterReadingDateField;
            }
            set
            {
                this.PreLastMeterReadingDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreLastMeterReadingDateSAPFormat
        {
            get
            {
                return this.PreLastMeterReadingDateSAPFormatField;
            }
            set
            {
                this.PreLastMeterReadingDateSAPFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreNetMeteringMeterRead
        {
            get
            {
                return this.PreNetMeteringMeterReadField;
            }
            set
            {
                this.PreNetMeteringMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreNormalMeterRead
        {
            get
            {
                return this.PreNormalMeterReadField;
            }
            set
            {
                this.PreNormalMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RateFactorGroup
        {
            get
            {
                return this.RateFactorGroupField;
            }
            set
            {
                this.RateFactorGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivableAmount
        {
            get
            {
                return this.ReceivableAmountField;
            }
            set
            {
                this.ReceivableAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecievableBalance
        {
            get
            {
                return this.RecievableBalanceField;
            }
            set
            {
                this.RecievableBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisterFactor
        {
            get
            {
                return this.RegisterFactorField;
            }
            set
            {
                this.RegisterFactorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettelmentBalance
        {
            get
            {
                return this.SettelmentBalanceField;
            }
            set
            {
                this.SettelmentBalanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriptionCode
        {
            get
            {
                return this.SubscriptionCodeField;
            }
            set
            {
                this.SubscriptionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriptionDescription
        {
            get
            {
                return this.SubscriptionDescriptionField;
            }
            set
            {
                this.SubscriptionDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriptionNo
        {
            get
            {
                return this.SubscriptionNoField;
            }
            set
            {
                this.SubscriptionNoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountStatement", Namespace="http://schemas.datacontract.org/2004/07/AllservicesIntegrationJepco.Classes")]
    public partial class AccountStatement : object
    {
        
        private SAPReference.AccountStatementDetails[] DetailsField;
        
        private SAPReference.AccountStatementHeader HeaderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAPReference.AccountStatementDetails[] Details
        {
            get
            {
                return this.DetailsField;
            }
            set
            {
                this.DetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAPReference.AccountStatementHeader Header
        {
            get
            {
                return this.HeaderField;
            }
            set
            {
                this.HeaderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountStatementHeader", Namespace="http://schemas.datacontract.org/2004/07/AllservicesIntegrationJepco.Classes")]
    public partial class AccountStatementHeader : object
    {
        
        private string AccountStatementBarCodeField;
        
        private string AccountStatementNoField;
        
        private string AdvancePaymentAmountField;
        
        private string ContractNoField;
        
        private string CustomerFirstNameField;
        
        private string CustomerLastNameField;
        
        private string DossierNumberField;
        
        private string FileNumberField;
        
        private string InstallationField;
        
        private string MeterNumberField;
        
        private string PrintDateField;
        
        private string ReceivablePaymentAmountField;
        
        private string SubscriptionNoField;
        
        private string SubscriptionTypeField;
        
        private string TotalAdvancePaymentAmountField;
        
        private string TotalReceivablePaymentAmountField;
        
        private string TotalReconnctionFeesAmountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountStatementBarCode
        {
            get
            {
                return this.AccountStatementBarCodeField;
            }
            set
            {
                this.AccountStatementBarCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountStatementNo
        {
            get
            {
                return this.AccountStatementNoField;
            }
            set
            {
                this.AccountStatementNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdvancePaymentAmount
        {
            get
            {
                return this.AdvancePaymentAmountField;
            }
            set
            {
                this.AdvancePaymentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractNo
        {
            get
            {
                return this.ContractNoField;
            }
            set
            {
                this.ContractNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFirstName
        {
            get
            {
                return this.CustomerFirstNameField;
            }
            set
            {
                this.CustomerFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerLastName
        {
            get
            {
                return this.CustomerLastNameField;
            }
            set
            {
                this.CustomerLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DossierNumber
        {
            get
            {
                return this.DossierNumberField;
            }
            set
            {
                this.DossierNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileNumber
        {
            get
            {
                return this.FileNumberField;
            }
            set
            {
                this.FileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Installation
        {
            get
            {
                return this.InstallationField;
            }
            set
            {
                this.InstallationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterNumber
        {
            get
            {
                return this.MeterNumberField;
            }
            set
            {
                this.MeterNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrintDate
        {
            get
            {
                return this.PrintDateField;
            }
            set
            {
                this.PrintDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivablePaymentAmount
        {
            get
            {
                return this.ReceivablePaymentAmountField;
            }
            set
            {
                this.ReceivablePaymentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriptionNo
        {
            get
            {
                return this.SubscriptionNoField;
            }
            set
            {
                this.SubscriptionNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriptionType
        {
            get
            {
                return this.SubscriptionTypeField;
            }
            set
            {
                this.SubscriptionTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalAdvancePaymentAmount
        {
            get
            {
                return this.TotalAdvancePaymentAmountField;
            }
            set
            {
                this.TotalAdvancePaymentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalReceivablePaymentAmount
        {
            get
            {
                return this.TotalReceivablePaymentAmountField;
            }
            set
            {
                this.TotalReceivablePaymentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalReconnctionFeesAmount
        {
            get
            {
                return this.TotalReconnctionFeesAmountField;
            }
            set
            {
                this.TotalReconnctionFeesAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountStatementDetails", Namespace="http://schemas.datacontract.org/2004/07/AllservicesIntegrationJepco.Classes")]
    public partial class AccountStatementDetails : object
    {
        
        private string BillAmountField;
        
        private string BillBarCodeField;
        
        private string BillNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillAmount
        {
            get
            {
                return this.BillAmountField;
            }
            set
            {
                this.BillAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillBarCode
        {
            get
            {
                return this.BillBarCodeField;
            }
            set
            {
                this.BillBarCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillNumber
        {
            get
            {
                return this.BillNumberField;
            }
            set
            {
                this.BillNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInformationBills", Namespace="http://schemas.datacontract.org/2004/07/AllservicesIntegrationJepco.Classes")]
    public partial class CustomerInformationBills : object
    {
        
        private SAPReference.CustomerInformationBillsDetails[] billsDetailsField;
        
        private SAPReference.CustomerInformationBillsHeader billsHeaderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAPReference.CustomerInformationBillsDetails[] billsDetails
        {
            get
            {
                return this.billsDetailsField;
            }
            set
            {
                this.billsDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SAPReference.CustomerInformationBillsHeader billsHeader
        {
            get
            {
                return this.billsHeaderField;
            }
            set
            {
                this.billsHeaderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerInformationBillsDetails", Namespace="http://schemas.datacontract.org/2004/07/AllservicesIntegrationJepco.Classes")]
    public partial class CustomerInformationBillsDetails : object
    {
        
        private string ActualMeterReadDateTimeField;
        
        private string BillPeriodField;
        
        private string BillingDocumentNoField;
        
        private string BillingFactorField;
        
        private string BusinessPartnarField;
        
        private string ClearingAmountField;
        
        private string ClearingDateField;
        
        private string ClearingDateSAPFormatField;
        
        private string ClearingStatusField;
        
        private string ConsumptionAmountField;
        
        private string ContractAccountField;
        
        private string ContractNumberField;
        
        private string CreationDateField;
        
        private string CreationDateSAPFormatField;
        
        private string DayConsumptionAmountField;
        
        private string DayMeterReadField;
        
        private string DocumantDateField;
        
        private string DocumantDateSAPFormatField;
        
        private string EbillingQuantityField;
        
        private string EndBillingPeriodField;
        
        private string EndBillingPeriodSAPFormatField;
        
        private string EquipmentNumberField;
        
        private string ExtraRubbishAmountField;
        
        private string FactorField;
        
        private string FileNumberField;
        
        private string FillsAmountField;
        
        private string FuelAmountField;
        
        private string GeneratedQtyField;
        
        private string IbillingQuantityField;
        
        private string InstallationField;
        
        private string InternalNumberField;
        
        private string KvarhmeterReadField;
        
        private string MainTransactionField;
        
        private string MaxDemandAmountField;
        
        private string MaxDemandMeterReadField;
        
        private string MeterNumberField;
        
        private string MeterRentAmountField;
        
        private string NetMeteringMeterReadField;
        
        private string NextCarryForwardCumQtyField;
        
        private string NightConsumptionAmountField;
        
        private string NightMeterReadField;
        
        private string NormalMeterReadField;
        
        private string OflagEmpField;
        
        private string PostingDateField;
        
        private string PostingDateSAPFormatField;
        
        private string PowerFactorAmountField;
        
        private string PrevCarryForwardCumQtyField;
        
        private string PrevDayMeterReadField;
        
        private string PrevKvarhmeterReadField;
        
        private string PrevMaxDemandMeterReadField;
        
        private string PrevNetMeteringMeterReadField;
        
        private string PrevNightMeterReadField;
        
        private string PrevNormalMeterReadField;
        
        private string PrintDocuamentField;
        
        private string RegisterFactorField;
        
        private string RubbishAmountField;
        
        private string SerialField;
        
        private string SettlementQuantityField;
        
        private string StartBillingPeriodField;
        
        private string StartBillingPeriodSAPFormatField;
        
        private string SubscriptionCodeField;
        
        private string SubscriptionDescriptionField;
        
        private string SubscriptionNoField;
        
        private string TelevisionAmountField;
        
        private string TotalBillAmountField;
        
        private string TotalRubbishAmountField;
        
        private string TransactionCurrancyField;
        
        private string UnClearingAmountField;
        
        private string WheelAmountField;
        
        private string YaDtaxAmountField;
        
        private string YkvahAmountField;
        private string billBarCodeField;

        [System.Runtime.Serialization.IgnoreDataMember]
        public string billBarCode
        {
            get
            {
                return this.billBarCodeField;
            }
            set
            {
                this.billBarCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActualMeterReadDateTime
        {
            get
            {
                return this.ActualMeterReadDateTimeField;
            }
            set
            {
                this.ActualMeterReadDateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillPeriod
        {
            get
            {
                return this.BillPeriodField;
            }
            set
            {
                this.BillPeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingDocumentNo
        {
            get
            {
                return this.BillingDocumentNoField;
            }
            set
            {
                this.BillingDocumentNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingFactor
        {
            get
            {
                return this.BillingFactorField;
            }
            set
            {
                this.BillingFactorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessPartnar
        {
            get
            {
                return this.BusinessPartnarField;
            }
            set
            {
                this.BusinessPartnarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClearingAmount
        {
            get
            {
                return this.ClearingAmountField;
            }
            set
            {
                this.ClearingAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClearingDate
        {
            get
            {
                return this.ClearingDateField;
            }
            set
            {
                this.ClearingDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClearingDateSAPFormat
        {
            get
            {
                return this.ClearingDateSAPFormatField;
            }
            set
            {
                this.ClearingDateSAPFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClearingStatus
        {
            get
            {
                return this.ClearingStatusField;
            }
            set
            {
                this.ClearingStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConsumptionAmount
        {
            get
            {
                return this.ConsumptionAmountField;
            }
            set
            {
                this.ConsumptionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractAccount
        {
            get
            {
                return this.ContractAccountField;
            }
            set
            {
                this.ContractAccountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractNumber
        {
            get
            {
                return this.ContractNumberField;
            }
            set
            {
                this.ContractNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreationDate
        {
            get
            {
                return this.CreationDateField;
            }
            set
            {
                this.CreationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreationDateSAPFormat
        {
            get
            {
                return this.CreationDateSAPFormatField;
            }
            set
            {
                this.CreationDateSAPFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DayConsumptionAmount
        {
            get
            {
                return this.DayConsumptionAmountField;
            }
            set
            {
                this.DayConsumptionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DayMeterRead
        {
            get
            {
                return this.DayMeterReadField;
            }
            set
            {
                this.DayMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumantDate
        {
            get
            {
                return this.DocumantDateField;
            }
            set
            {
                this.DocumantDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumantDateSAPFormat
        {
            get
            {
                return this.DocumantDateSAPFormatField;
            }
            set
            {
                this.DocumantDateSAPFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EbillingQuantity
        {
            get
            {
                return this.EbillingQuantityField;
            }
            set
            {
                this.EbillingQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndBillingPeriod
        {
            get
            {
                return this.EndBillingPeriodField;
            }
            set
            {
                this.EndBillingPeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EndBillingPeriodSAPFormat
        {
            get
            {
                return this.EndBillingPeriodSAPFormatField;
            }
            set
            {
                this.EndBillingPeriodSAPFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EquipmentNumber
        {
            get
            {
                return this.EquipmentNumberField;
            }
            set
            {
                this.EquipmentNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraRubbishAmount
        {
            get
            {
                return this.ExtraRubbishAmountField;
            }
            set
            {
                this.ExtraRubbishAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Factor
        {
            get
            {
                return this.FactorField;
            }
            set
            {
                this.FactorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileNumber
        {
            get
            {
                return this.FileNumberField;
            }
            set
            {
                this.FileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FillsAmount
        {
            get
            {
                return this.FillsAmountField;
            }
            set
            {
                this.FillsAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FuelAmount
        {
            get
            {
                return this.FuelAmountField;
            }
            set
            {
                this.FuelAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GeneratedQty
        {
            get
            {
                return this.GeneratedQtyField;
            }
            set
            {
                this.GeneratedQtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IbillingQuantity
        {
            get
            {
                return this.IbillingQuantityField;
            }
            set
            {
                this.IbillingQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Installation
        {
            get
            {
                return this.InstallationField;
            }
            set
            {
                this.InstallationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternalNumber
        {
            get
            {
                return this.InternalNumberField;
            }
            set
            {
                this.InternalNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KvarhmeterRead
        {
            get
            {
                return this.KvarhmeterReadField;
            }
            set
            {
                this.KvarhmeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainTransaction
        {
            get
            {
                return this.MainTransactionField;
            }
            set
            {
                this.MainTransactionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaxDemandAmount
        {
            get
            {
                return this.MaxDemandAmountField;
            }
            set
            {
                this.MaxDemandAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MaxDemandMeterRead
        {
            get
            {
                return this.MaxDemandMeterReadField;
            }
            set
            {
                this.MaxDemandMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterNumber
        {
            get
            {
                return this.MeterNumberField;
            }
            set
            {
                this.MeterNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterRentAmount
        {
            get
            {
                return this.MeterRentAmountField;
            }
            set
            {
                this.MeterRentAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NetMeteringMeterRead
        {
            get
            {
                return this.NetMeteringMeterReadField;
            }
            set
            {
                this.NetMeteringMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NextCarryForwardCumQty
        {
            get
            {
                return this.NextCarryForwardCumQtyField;
            }
            set
            {
                this.NextCarryForwardCumQtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NightConsumptionAmount
        {
            get
            {
                return this.NightConsumptionAmountField;
            }
            set
            {
                this.NightConsumptionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NightMeterRead
        {
            get
            {
                return this.NightMeterReadField;
            }
            set
            {
                this.NightMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NormalMeterRead
        {
            get
            {
                return this.NormalMeterReadField;
            }
            set
            {
                this.NormalMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OflagEmp
        {
            get
            {
                return this.OflagEmpField;
            }
            set
            {
                this.OflagEmpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostingDate
        {
            get
            {
                return this.PostingDateField;
            }
            set
            {
                this.PostingDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostingDateSAPFormat
        {
            get
            {
                return this.PostingDateSAPFormatField;
            }
            set
            {
                this.PostingDateSAPFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PowerFactorAmount
        {
            get
            {
                return this.PowerFactorAmountField;
            }
            set
            {
                this.PowerFactorAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrevCarryForwardCumQty
        {
            get
            {
                return this.PrevCarryForwardCumQtyField;
            }
            set
            {
                this.PrevCarryForwardCumQtyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrevDayMeterRead
        {
            get
            {
                return this.PrevDayMeterReadField;
            }
            set
            {
                this.PrevDayMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrevKvarhmeterRead
        {
            get
            {
                return this.PrevKvarhmeterReadField;
            }
            set
            {
                this.PrevKvarhmeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrevMaxDemandMeterRead
        {
            get
            {
                return this.PrevMaxDemandMeterReadField;
            }
            set
            {
                this.PrevMaxDemandMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrevNetMeteringMeterRead
        {
            get
            {
                return this.PrevNetMeteringMeterReadField;
            }
            set
            {
                this.PrevNetMeteringMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrevNightMeterRead
        {
            get
            {
                return this.PrevNightMeterReadField;
            }
            set
            {
                this.PrevNightMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrevNormalMeterRead
        {
            get
            {
                return this.PrevNormalMeterReadField;
            }
            set
            {
                this.PrevNormalMeterReadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrintDocuament
        {
            get
            {
                return this.PrintDocuamentField;
            }
            set
            {
                this.PrintDocuamentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegisterFactor
        {
            get
            {
                return this.RegisterFactorField;
            }
            set
            {
                this.RegisterFactorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RubbishAmount
        {
            get
            {
                return this.RubbishAmountField;
            }
            set
            {
                this.RubbishAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Serial
        {
            get
            {
                return this.SerialField;
            }
            set
            {
                this.SerialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SettlementQuantity
        {
            get
            {
                return this.SettlementQuantityField;
            }
            set
            {
                this.SettlementQuantityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartBillingPeriod
        {
            get
            {
                return this.StartBillingPeriodField;
            }
            set
            {
                this.StartBillingPeriodField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StartBillingPeriodSAPFormat
        {
            get
            {
                return this.StartBillingPeriodSAPFormatField;
            }
            set
            {
                this.StartBillingPeriodSAPFormatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriptionCode
        {
            get
            {
                return this.SubscriptionCodeField;
            }
            set
            {
                this.SubscriptionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriptionDescription
        {
            get
            {
                return this.SubscriptionDescriptionField;
            }
            set
            {
                this.SubscriptionDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubscriptionNo
        {
            get
            {
                return this.SubscriptionNoField;
            }
            set
            {
                this.SubscriptionNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelevisionAmount
        {
            get
            {
                return this.TelevisionAmountField;
            }
            set
            {
                this.TelevisionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalBillAmount
        {
            get
            {
                return this.TotalBillAmountField;
            }
            set
            {
                this.TotalBillAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalRubbishAmount
        {
            get
            {
                return this.TotalRubbishAmountField;
            }
            set
            {
                this.TotalRubbishAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionCurrancy
        {
            get
            {
                return this.TransactionCurrancyField;
            }
            set
            {
                this.TransactionCurrancyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnClearingAmount
        {
            get
            {
                return this.UnClearingAmountField;
            }
            set
            {
                this.UnClearingAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WheelAmount
        {
            get
            {
                return this.WheelAmountField;
            }
            set
            {
                this.WheelAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YaDtaxAmount
        {
            get
            {
                return this.YaDtaxAmountField;
            }
            set
            {
                this.YaDtaxAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YkvahAmount
        {
            get
            {
                return this.YkvahAmountField;
            }
            set
            {
                this.YkvahAmountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateBillResponse", Namespace="http://schemas.datacontract.org/2004/07/AllservicesIntegrationJepco.Classes")]
    public partial class CreateBillResponse : object
    {
        
        private string DescriptionField;
        
        private string StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderDetails", Namespace="http://schemas.datacontract.org/2004/07/AllservicesIntegrationJepco.Classes")]
    public partial class OrderDetails : object
    {
        
        private string CurrentLevelField;
        
        private string CustomernameField;
        
        private string MappingCodeField;
        
        private string MessageField;
        
        private string NotifiNoField;
        
        private string OrderDateField;
        
        private string OrderTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentLevel
        {
            get
            {
                return this.CurrentLevelField;
            }
            set
            {
                this.CurrentLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Customername
        {
            get
            {
                return this.CustomernameField;
            }
            set
            {
                this.CustomernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MappingCode
        {
            get
            {
                return this.MappingCodeField;
            }
            set
            {
                this.MappingCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotifiNo
        {
            get
            {
                return this.NotifiNoField;
            }
            set
            {
                this.NotifiNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderType
        {
            get
            {
                return this.OrderTypeField;
            }
            set
            {
                this.OrderTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SAPReference.ISapServices")]
    public interface ISapServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapServices/GetBillsSingleCustomerInfo", ReplyAction="http://tempuri.org/ISapServices/GetBillsSingleCustomerInfoResponse")]
        System.Threading.Tasks.Task<SAPReference.CustomerInformationBillsHeader> GetBillsSingleCustomerInfoAsync(string FileNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapServices/GetBillsSingleCustomerSum", ReplyAction="http://tempuri.org/ISapServices/GetBillsSingleCustomerSumResponse")]
        System.Threading.Tasks.Task<SAPReference.AccountStatement> GetBillsSingleCustomerSumAsync(string FileNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapServices/GetBillsSingleCustomer", ReplyAction="http://tempuri.org/ISapServices/GetBillsSingleCustomerResponse")]
        System.Threading.Tasks.Task<SAPReference.CustomerInformationBills> GetBillsSingleCustomerAsync(string FileNumber, string AllInfo, string ClearedStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapServices/GetBillsSingleCustomerSim", ReplyAction="http://tempuri.org/ISapServices/GetBillsSingleCustomerSimResponse")]
        System.Threading.Tasks.Task<SAPReference.CustomerInformationBills> GetBillsSingleCustomerSimAsync(string FileNumber, string UseMeterRead, long FirstMeterReadingRecorded, long PreFirstMeterReadingRecorded, string FactGroup, string RateCategory, string UseConsumption, long FirstPeriodConsumption, long SecondMeterReadingRecorded, long PreSecondMeterReadingRecorded, long SecondPeriodConsumption);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapServices/CraeteMobileBillsSingleCustomer", ReplyAction="http://tempuri.org/ISapServices/CraeteMobileBillsSingleCustomerResponse")]
        System.Threading.Tasks.Task<SAPReference.CreateBillResponse> CraeteMobileBillsSingleCustomerAsync(string Installation, string FileNumber, string FirstReadingNumber, string SecondReadingNumber, string OrderMeterReadingDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISapServices/OrderStatus", ReplyAction="http://tempuri.org/ISapServices/OrderStatusResponse")]
        System.Threading.Tasks.Task<SAPReference.OrderDetails[]> OrderStatusAsync(string OrderNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISapServicesChannel : SAPReference.ISapServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SapServicesClient : System.ServiceModel.ClientBase<SAPReference.ISapServices>, SAPReference.ISapServices
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SapServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(SapServicesClient.GetBindingForEndpoint(endpointConfiguration), SapServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SapServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SapServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SapServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SapServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SapServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<SAPReference.CustomerInformationBillsHeader> GetBillsSingleCustomerInfoAsync(string FileNumber)
        {
            return base.Channel.GetBillsSingleCustomerInfoAsync(FileNumber);
        }
        
        public System.Threading.Tasks.Task<SAPReference.AccountStatement> GetBillsSingleCustomerSumAsync(string FileNumber)
        {
            return base.Channel.GetBillsSingleCustomerSumAsync(FileNumber);
        }
        
        public System.Threading.Tasks.Task<SAPReference.CustomerInformationBills> GetBillsSingleCustomerAsync(string FileNumber, string AllInfo, string ClearedStatus)
        {
            return base.Channel.GetBillsSingleCustomerAsync(FileNumber, AllInfo, ClearedStatus);
        }
        
        public System.Threading.Tasks.Task<SAPReference.CustomerInformationBills> GetBillsSingleCustomerSimAsync(string FileNumber, string UseMeterRead, long FirstMeterReadingRecorded, long PreFirstMeterReadingRecorded, string FactGroup, string RateCategory, string UseConsumption, long FirstPeriodConsumption, long SecondMeterReadingRecorded, long PreSecondMeterReadingRecorded, long SecondPeriodConsumption)
        {
            return base.Channel.GetBillsSingleCustomerSimAsync(FileNumber, UseMeterRead, FirstMeterReadingRecorded, PreFirstMeterReadingRecorded, FactGroup, RateCategory, UseConsumption, FirstPeriodConsumption, SecondMeterReadingRecorded, PreSecondMeterReadingRecorded, SecondPeriodConsumption);
        }
        
        public System.Threading.Tasks.Task<SAPReference.CreateBillResponse> CraeteMobileBillsSingleCustomerAsync(string Installation, string FileNumber, string FirstReadingNumber, string SecondReadingNumber, string OrderMeterReadingDate)
        {
            return base.Channel.CraeteMobileBillsSingleCustomerAsync(Installation, FileNumber, FirstReadingNumber, SecondReadingNumber, OrderMeterReadingDate);
        }
        
        public System.Threading.Tasks.Task<SAPReference.OrderDetails[]> OrderStatusAsync(string OrderNo)
        {
            return base.Channel.OrderStatusAsync(OrderNo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISapServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ISapServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISapServices))
            {
                return new System.ServiceModel.EndpointAddress("http://mobile.jep.local/SAPIntegration/SapServices.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ISapServices))
            {
                return new System.ServiceModel.EndpointAddress("https://mobile.jepco.com.jo/SAPIntegration/SapServices.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISapServices,
            
            BasicHttpsBinding_ISapServices,
        }
    }
}
