//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenaTrackService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallCenterResponses", Namespace="http://schemas.datacontract.org/2004/07/AllservicesIntegrationJepco.Classes")]
    public partial class CallCenterResponses : object
    {
        
        private string CodeBehaviorField;
        
        private string CodeIdField;
        
        private string CodeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeBehavior
        {
            get
            {
                return this.CodeBehaviorField;
            }
            set
            {
                this.CodeBehaviorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeId
        {
            get
            {
                return this.CodeIdField;
            }
            set
            {
                this.CodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodeName
        {
            get
            {
                return this.CodeNameField;
            }
            set
            {
                this.CodeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallCenterIssueResponse", Namespace="http://schemas.datacontract.org/2004/07/AllservicesIntegrationJepco.Classes")]
    public partial class CallCenterIssueResponse : object
    {
        
        private long ComplainIssueIdField;
        
        private string ComplainRefrenceNumberField;
        
        private string ComplainStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ComplainIssueId
        {
            get
            {
                return this.ComplainIssueIdField;
            }
            set
            {
                this.ComplainIssueIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComplainRefrenceNumber
        {
            get
            {
                return this.ComplainRefrenceNumberField;
            }
            set
            {
                this.ComplainRefrenceNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComplainStatus
        {
            get
            {
                return this.ComplainStatusField;
            }
            set
            {
                this.ComplainStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallLoginResponses", Namespace="http://schemas.datacontract.org/2004/07/AllservicesIntegrationJepco.Classes")]
    public partial class CallLoginResponses : object
    {
        
        private int BranchIDField;
        
        private string FullNameField;
        
        private int LangField;
        
        private int UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BranchID
        {
            get
            {
                return this.BranchIDField;
            }
            set
            {
                this.BranchIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName
        {
            get
            {
                return this.FullNameField;
            }
            set
            {
                this.FullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JEPCOViewRequestsParentsResponse", Namespace="http://schemas.datacontract.org/2004/07/AllservicesIntegrationJepco.Classes")]
    public partial class JEPCOViewRequestsParentsResponse : object
    {
        
        private string AddressLattField;
        
        private string AddressLongField;
        
        private string BuildingNOField;
        
        private System.DateTime ComplaintDateField;
        
        private string ComplaintDescriptionField;
        
        private string CustomerFileNumberField;
        
        private string CustomerMobileNumberField;
        
        private string CustomerNameField;
        
        private string DistrictField;
        
        private System.Nullable<int> DistrictIDField;
        
        private string GovernateField;
        
        private System.Nullable<int> GovernateIDField;
        
        private decimal IssueIDField;
        
        private string IssueTitleField;
        
        private string LVFeederNumberField;
        
        private string MVFeederNumberField;
        
        private string MVFeederNumber1Field;
        
        private string MeterNumberField;
        
        private string ParentRefcodeField;
        
        private string PriorityDescField;
        
        private string RefcodeField;
        
        private string StatusDescField;
        
        private string StreetField;
        
        private System.Nullable<int> StreetIDField;
        
        private string SubstationNumberField;
        
        private System.Nullable<int> ZoneIDField;
        
        private string ZoneNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLatt
        {
            get
            {
                return this.AddressLattField;
            }
            set
            {
                this.AddressLattField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLong
        {
            get
            {
                return this.AddressLongField;
            }
            set
            {
                this.AddressLongField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingNO
        {
            get
            {
                return this.BuildingNOField;
            }
            set
            {
                this.BuildingNOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ComplaintDate
        {
            get
            {
                return this.ComplaintDateField;
            }
            set
            {
                this.ComplaintDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComplaintDescription
        {
            get
            {
                return this.ComplaintDescriptionField;
            }
            set
            {
                this.ComplaintDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFileNumber
        {
            get
            {
                return this.CustomerFileNumberField;
            }
            set
            {
                this.CustomerFileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerMobileNumber
        {
            get
            {
                return this.CustomerMobileNumberField;
            }
            set
            {
                this.CustomerMobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName
        {
            get
            {
                return this.CustomerNameField;
            }
            set
            {
                this.CustomerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string District
        {
            get
            {
                return this.DistrictField;
            }
            set
            {
                this.DistrictField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DistrictID
        {
            get
            {
                return this.DistrictIDField;
            }
            set
            {
                this.DistrictIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Governate
        {
            get
            {
                return this.GovernateField;
            }
            set
            {
                this.GovernateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GovernateID
        {
            get
            {
                return this.GovernateIDField;
            }
            set
            {
                this.GovernateIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal IssueID
        {
            get
            {
                return this.IssueIDField;
            }
            set
            {
                this.IssueIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IssueTitle
        {
            get
            {
                return this.IssueTitleField;
            }
            set
            {
                this.IssueTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LVFeederNumber
        {
            get
            {
                return this.LVFeederNumberField;
            }
            set
            {
                this.LVFeederNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MVFeederNumber
        {
            get
            {
                return this.MVFeederNumberField;
            }
            set
            {
                this.MVFeederNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MVFeederNumber1
        {
            get
            {
                return this.MVFeederNumber1Field;
            }
            set
            {
                this.MVFeederNumber1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MeterNumber
        {
            get
            {
                return this.MeterNumberField;
            }
            set
            {
                this.MeterNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentRefcode
        {
            get
            {
                return this.ParentRefcodeField;
            }
            set
            {
                this.ParentRefcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriorityDesc
        {
            get
            {
                return this.PriorityDescField;
            }
            set
            {
                this.PriorityDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Refcode
        {
            get
            {
                return this.RefcodeField;
            }
            set
            {
                this.RefcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDesc
        {
            get
            {
                return this.StatusDescField;
            }
            set
            {
                this.StatusDescField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street
        {
            get
            {
                return this.StreetField;
            }
            set
            {
                this.StreetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StreetID
        {
            get
            {
                return this.StreetIDField;
            }
            set
            {
                this.StreetIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubstationNumber
        {
            get
            {
                return this.SubstationNumberField;
            }
            set
            {
                this.SubstationNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ZoneID
        {
            get
            {
                return this.ZoneIDField;
            }
            set
            {
                this.ZoneIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZoneName
        {
            get
            {
                return this.ZoneNameField;
            }
            set
            {
                this.ZoneNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MenaTrackService.ICallCenterNew")]
    public interface ICallCenterNew
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterNew/GetCities", ReplyAction="http://tempuri.org/ICallCenterNew/GetCitiesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.CallCenterResponses>> GetCitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterNew/GetComplaintType", ReplyAction="http://tempuri.org/ICallCenterNew/GetComplaintTypeResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.CallCenterResponses>> GetComplaintTypeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterNew/GetAreas", ReplyAction="http://tempuri.org/ICallCenterNew/GetAreasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.CallCenterResponses>> GetAreasAsync(int BranchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterNew/GetNeighborhoods", ReplyAction="http://tempuri.org/ICallCenterNew/GetNeighborhoodsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.CallCenterResponses>> GetNeighborhoodsAsync(int BranchId, int AreaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterNew/GetStreets", ReplyAction="http://tempuri.org/ICallCenterNew/GetStreetsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.CallCenterResponses>> GetStreetsAsync(int BranchId, int NeighborhoodId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterNew/SaveIssue", ReplyAction="http://tempuri.org/ICallCenterNew/SaveIssueResponse")]
        System.Threading.Tasks.Task<MenaTrackService.CallCenterIssueResponse> SaveIssueAsync(int BranchID, string MobileNumber, string RequesterName, string MeterNumber, int ComplaintId, int AreaId, int NeighborhoodId, int StreetId, string IssueTitle, string IssueDescription, int FailureTypeID, string AttachName, string AttachValue, string AddtiionalFileds, int intIntegrationType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterNew/IssueStatus", ReplyAction="http://tempuri.org/ICallCenterNew/IssueStatusResponse")]
        System.Threading.Tasks.Task<MenaTrackService.CallCenterIssueResponse> IssueStatusAsync(int BranchID, string ComplainRefrenceNumber, long ComplainIssueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterNew/JepcoLogin", ReplyAction="http://tempuri.org/ICallCenterNew/JepcoLoginResponse")]
        System.Threading.Tasks.Task<MenaTrackService.CallLoginResponses> JepcoLoginAsync(string UserName, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterNew/JepcoLogout", ReplyAction="http://tempuri.org/ICallCenterNew/JepcoLogoutResponse")]
        System.Threading.Tasks.Task<bool> JepcoLogoutAsync(int UserId, int BranchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterNew/JEPCO_ViewRequests_Parents", ReplyAction="http://tempuri.org/ICallCenterNew/JEPCO_ViewRequests_ParentsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.JEPCOViewRequestsParentsResponse>> JEPCO_ViewRequests_ParentsAsync(int UserId, int BranchID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICallCenterNew/JEPCO_ViewRequests_Childs", ReplyAction="http://tempuri.org/ICallCenterNew/JEPCO_ViewRequests_ChildsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.JEPCOViewRequestsParentsResponse>> JEPCO_ViewRequests_ChildsAsync(int IssueID, int BranchID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ICallCenterNewChannel : MenaTrackService.ICallCenterNew, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class CallCenterNewClient : System.ServiceModel.ClientBase<MenaTrackService.ICallCenterNew>, MenaTrackService.ICallCenterNew
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CallCenterNewClient(EndpointConfiguration endpointConfiguration) : 
                base(CallCenterNewClient.GetBindingForEndpoint(endpointConfiguration), CallCenterNewClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CallCenterNewClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CallCenterNewClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CallCenterNewClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CallCenterNewClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CallCenterNewClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.CallCenterResponses>> GetCitiesAsync()
        {
            return base.Channel.GetCitiesAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.CallCenterResponses>> GetComplaintTypeAsync()
        {
            return base.Channel.GetComplaintTypeAsync();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.CallCenterResponses>> GetAreasAsync(int BranchId)
        {
            return base.Channel.GetAreasAsync(BranchId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.CallCenterResponses>> GetNeighborhoodsAsync(int BranchId, int AreaId)
        {
            return base.Channel.GetNeighborhoodsAsync(BranchId, AreaId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.CallCenterResponses>> GetStreetsAsync(int BranchId, int NeighborhoodId)
        {
            return base.Channel.GetStreetsAsync(BranchId, NeighborhoodId);
        }
        
        public System.Threading.Tasks.Task<MenaTrackService.CallCenterIssueResponse> SaveIssueAsync(int BranchID, string MobileNumber, string RequesterName, string MeterNumber, int ComplaintId, int AreaId, int NeighborhoodId, int StreetId, string IssueTitle, string IssueDescription, int FailureTypeID, string AttachName, string AttachValue, string AddtiionalFileds, int intIntegrationType)
        {
            return base.Channel.SaveIssueAsync(BranchID, MobileNumber, RequesterName, MeterNumber, ComplaintId, AreaId, NeighborhoodId, StreetId, IssueTitle, IssueDescription, FailureTypeID, AttachName, AttachValue, AddtiionalFileds, intIntegrationType);
        }
        
        public System.Threading.Tasks.Task<MenaTrackService.CallCenterIssueResponse> IssueStatusAsync(int BranchID, string ComplainRefrenceNumber, long ComplainIssueId)
        {
            return base.Channel.IssueStatusAsync(BranchID, ComplainRefrenceNumber, ComplainIssueId);
        }
        
        public System.Threading.Tasks.Task<MenaTrackService.CallLoginResponses> JepcoLoginAsync(string UserName, string Password)
        {
            return base.Channel.JepcoLoginAsync(UserName, Password);
        }
        
        public System.Threading.Tasks.Task<bool> JepcoLogoutAsync(int UserId, int BranchID)
        {
            return base.Channel.JepcoLogoutAsync(UserId, BranchID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.JEPCOViewRequestsParentsResponse>> JEPCO_ViewRequests_ParentsAsync(int UserId, int BranchID)
        {
            return base.Channel.JEPCO_ViewRequests_ParentsAsync(UserId, BranchID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<MenaTrackService.JEPCOViewRequestsParentsResponse>> JEPCO_ViewRequests_ChildsAsync(int IssueID, int BranchID)
        {
            return base.Channel.JEPCO_ViewRequests_ChildsAsync(IssueID, BranchID);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICallCenterNew))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ICallCenterNew))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICallCenterNew))
            {
                return new System.ServiceModel.EndpointAddress("http://mobile-app.jep.local/SAPIntegration/CallCenterNew.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ICallCenterNew))
            {
                return new System.ServiceModel.EndpointAddress("https://mobile.jepco.com.jo:8443/SAPIntegration/CallCenterNew.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICallCenterNew,
            
            BasicHttpsBinding_ICallCenterNew,
        }
    }
}
